### PR TITLE
Support for the size and annotation properties.

### PR DESCRIPTION
**Pull request by rodrigograca31**
As the title says....
It's probably my third time writing java code but I think it's well coded! :)

### CODE REVIEW

**Comment by rodrigograca31** [comment]
More info here: [https://developers.google.com/android/reference/com/google/android/gms/plus/PlusOneButton.html](https://developers.google.com/android/reference/com/google/android/gms/plus/PlusOneButton.html)

**Comment by jcesarmobile** [comment]
Thanks for the PR. It looks good, but can you change `size = obj.optInt("size", 0);` to `size = obj.optInt("size", 3);`?  The default value of the size is SIZE_STANDARD

**Comment by rodrigograca31** [comment]
I thought the defaults where 0 and 0 but I didn't check...
In the documentation says that the default value of size is `SIZE_STANDARD` and annotation should be `ANNOTATION_BUBBLE` right?

**Comment by rodrigograca31** [comment]
Done.

**Comment by jcesarmobile** [comment]
merged, thanks!

Yes, default is bubble

**Pull request merged**
